name: ðŸ™ˆ Backstop & Docker CI
run-name: "CI running on ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"
# Tests backstopjs alone, docker build, docker push to
# ghcr.io, docker pull from ghcr.io, and backstopjs in
# the docker docker build.

on:
  workflow_dispatch:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  packages: write

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name }}

jobs:
  # backstop-sanity-docker-test:
  #   name: Sanity Test Backstop
  #   uses: ./.github/workflows/backstop-sanity-docker.yml
    
  backstop-sanity-test:
    name: Sanity Test Backstop
    uses: ./.github/workflows/backstop-sanity-test.yml

  # backstop-smoke-test:
  #   name: Smoke Test Backstop
  #   uses: ./.github/workflows/backstop-smoke-test.yml

  # backstop-integration-test:
  #   name: Integration Test Backstop
  #   uses: ./.github/workflows/backstop-integration-test.yml

  # build-publish-docker:
  #   name: Build Docker
  #   uses: ./.github/workflows/docker-build.yml

  # docker-sanity-test:
  #   needs: build-publish-docker
  #   name: Sanity Test Docker
  #   uses: ./.github/workflows/docker-sanity-test.yml

  # docker-smoke-test:
  #   needs: build-publish-docker
  #   name: Smoke Test Docker
  #   uses: ./.github/workflows/docker-smoke-test.yml

  # build-compare:
  #   name: Build Compare UI
  #   uses: ./.github/workflows/build-compare.yml
